---
title: "Data preparation"
output: html_document
date: "2023-09-12"
---

```{r eval=FALSE, include=FALSE}
# Load relevant packages
install.packages("tidyverse")
install.packages("dplyr")
install.packages("data.table")
library(tidyverse)
library(dplyr)
library(data.table)
```

Use 3 datasets (in no particular order):

1.title.episode.tsv.gz to get the number of seasons (length of series)

2.title.ratings.tsv.gz to get the overall rating of the show

3.title.basics.tsv.gz to get the name of the show

```{r}
#Download relevant datasets
urls = c("https://datasets.imdbws.com/title.episode.tsv.gz", "https://datasets.imdbws.com/title.ratings.tsv.gz", "https://datasets.imdbws.com/title.basics.tsv.gz")
for (url in urls) {
  filename =  paste(gsub('[^a-zA-Z]', '',url), '.tsv')
  filename = gsub('httpsdatasetsimdbwscom', '', filename)
  download.file(url, destfile = filename)
}

```

Load datasets

```{r}
episodes <- read_tsv('titleepisodetsvgz .tsv')
rating <- read_tsv('titleratingstsvgz .tsv')
names <- read_tsv('titlebasicstsvgz .tsv')
```

Count unique series and look at long series (seasons \>= 5)

```{r}
library(dplyr)

#group by parentTconst and seasonNumber
max_seasons <- episodes %>%
  group_by(parentTconst) %>%
  summarise(max_season = max(seasonNumber))

#filter the seasonNumber >=5
long_series_1 <- max_seasons %>%
  filter(max_season >= 5)

#rename the parentTconst to tconst
long_series_1 <- long_series_1 %>% rename(tconst = parentTconst)

#merged dataset again
merge1 <- left_join(long_series_1, rating, by = 'tconst')

#create new dataset for names
names_years <- names %>%
  select(tconst, startYear, endYear)

#merged dataset with names and years
merge2 <- left_join(merge1, names_years, by = 'tconst')
```
